name             'app_add_apt'
maintainer       'Earth U'
maintainer_email 'iskitingbords@gmail.com'
license          'Apache-2.0'
description      'Add apt repository in Ubuntu'
source_url       'https://github.com/nollieheel/app_add_apt'
issues_url       'https://github.com/nollieheel/app_add_apt/issues'
version          '1.0.0'
chef_version     '>= 18.3'
supports         'ubuntu', '22.04'
